http {
    server {
        location / {
            root /html;
            index index.html index.htm;
 
            # 开启缓存
            add_header Cache-Control "public";
 
            # 设置缓存时间为 1 天
            expires 1d;
 
            # 根据文件类型设置不同的缓存时间
            if ($request_filename ~* ^.+\.(js|css)$) {
                # 缓存时间为 1 小时
                expires 1h;
            }
            if ($request_filename ~* ^.+\.(png|gif|jpg|jpeg|bmp)$) {
                # 缓存时间为 7 天
                expires 7d;
            }
        }
    }
}